// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR3BDwvH_Ol4XvsYl01Sxhb2y3oGNjWGI',
    appId: '1:604969157640:web:35ff872f33d61150213dbd',
    messagingSenderId: '604969157640',
    projectId: 'first-app-firebase-063',
    authDomain: 'first-app-firebase-063.firebaseapp.com',
    storageBucket: 'first-app-firebase-063.appspot.com',
    measurementId: 'G-9PLV6J5FLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0C-gWKcLjhAfaLOwMbUTnXpHHUMheymw',
    appId: '1:604969157640:android:ed40ca9eb8e1b22d213dbd',
    messagingSenderId: '604969157640',
    projectId: 'first-app-firebase-063',
    storageBucket: 'first-app-firebase-063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPjyzfpMKDgqEHWiNLWV865SKIVjO-qXU',
    appId: '1:604969157640:ios:442034c63cc2f643213dbd',
    messagingSenderId: '604969157640',
    projectId: 'first-app-firebase-063',
    storageBucket: 'first-app-firebase-063.appspot.com',
    iosBundleId: 'com.example.firstAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPjyzfpMKDgqEHWiNLWV865SKIVjO-qXU',
    appId: '1:604969157640:ios:442034c63cc2f643213dbd',
    messagingSenderId: '604969157640',
    projectId: 'first-app-firebase-063',
    storageBucket: 'first-app-firebase-063.appspot.com',
    iosBundleId: 'com.example.firstAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR3BDwvH_Ol4XvsYl01Sxhb2y3oGNjWGI',
    appId: '1:604969157640:web:ed460b232d48b470213dbd',
    messagingSenderId: '604969157640',
    projectId: 'first-app-firebase-063',
    authDomain: 'first-app-firebase-063.firebaseapp.com',
    storageBucket: 'first-app-firebase-063.appspot.com',
    measurementId: 'G-2XB956XEZL',
  );

}